name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run linter Ejercicios
      run: python -m pylint UD1_Python/Ejercicios

    - name: Run tests Ejercicios
      run: python -m pytest UD1_Python/Ejercicios/tests/ -v -s