name: CI

on:
  push:
    branches:
      - main
      - develop
      - master
  pull_request:
    branches:
      - main
      - develop
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest

      - name: Run Pylint
        run: |
          # Usa la configuración de .pylintrc
          python -m pylint UD1_Python

      - name: Run Tests
        run: |
          # Añadimos el repo raíz al PYTHONPATH para que pytest encuentre UD1_Python
          PYTHONPATH=. python -m pytest UD1_Python/tests -v -s