name: Python CI  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PRACTICA: UD1_Python/Practica_Vigenere  # ajusta según práctica
      CENTRAL_REPO: 25_26-ADAT-UDA

    steps:
      # 1. Checkout del repo actual (alumno o tuyo)
      - name: Checkout current repo
        uses: actions/checkout@v4

      # 2. Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Si estamos en el repo del alumno: bajar tests desde tu repo central
      - name: Download official tests (only if not central repo)
        if: github.repository != 'ADAT-2526-CJ/25_26-ADAT-UDA'
        run: |
          echo "Descargando tests oficiales de $PRACTICA..."
          git clone --depth 1 --filter=blob:none --sparse https://github.com/ADAT-2526-CJ/25_26-ADAT-UDA tmp_tests
          cd tmp_tests
          git sparse-checkout set $PRACTICA/tests
          cd ..
          mkdir -p tests
          cp -r tmp_tests/$PRACTICA/tests/* ./tests/

      # 4. Instalar dependencias si hay
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest

      # 5. Ejecutar el linter para comprobar estilo y buenas prácticas
      - name: Run linter
        run: pylint src

      # 6. Ejecutar los tests oficiales con detalle (-v) y mostrando prints (-s)
      - name: Run tests
        run: pytest -v -s
